// seed categories table
exports.seed = async function (knex) {
  await knex('users').del()
  await knex('users').insert([
    {
      id: 1,
      auth0_id: 'auth0|62734d140b600f00693e3f51',
      first_name: 'Tracey',
      last_name: 'Anon',
      username: 'Traceyliveshere',
      email: 'tracey@doghome.com',
      about:
        'I love all things Vampire! I am pretty good at fencing and Brazilian Jiu Jitsu and keen to find someone to teach me how to sing; Tuvan Throat singing style in particular. Would also love to learn knitting to make coats for my blessing of cats.',
      rating: 4,
      region: 'Bay of Plenty',
      picture: '/_tracey.jpeg',
    },
    {
      id: 2,
      auth0_id: 'auth0|62734d140b600f00693e3f50',
      first_name: 'Kinley',
      last_name: 'Zhang',
      username: 'Zhandel',
      email: 'eruditesnail@togamail.com',
      about:
        'Looking for help to get me onto the next series of Masterchef. I need most help with pasteries and baking. When not cooking I love to rock climb, roller derby and play drums and in my gaze-pop band; Six degrees of javascript destructuring',
      rating: 3,
      region: 'Taranaki',
    },
    {
      id: 3,
      auth0_id: 'auth0|62733e75737d38006ab5d194',
      first_name: 'Garrett',
      last_name: 'Do-ble',
      username: 'Gdog',
      email: 'garrettwon@gmail.com',
      about: 'I love myself, what about you?',
      rating: 5,
      region: 'Auckland',
      picture: '/_garrett.jpeg',
    },
    {
      id: 4,
      auth0_id: 'auth0|62734d140b600f00693e3f52',
      first_name: 'Bennito',
      last_name: 'De Silva',
      username: '1stBen',
      email: 'whodafiam@twitch.com',
      about:
        'My friends call me Ben, I stream on twitch. Can anyone teach me how to drive? Have failed my restricted license 3 times this month. Can teach you gaming and also am pretty decent at airsoft. Am the biggest fan of My little Unicorns.',
      rating: 4,
      region: 'Auckland',
      picture: '/_benneto.jpeg',
    },
    {
      id: 5,
      auth0_id: 'auth0|62734d140b600f00693e3f53',
      first_name: 'Terrance Trent',
      last_name: 'Darby',
      username: 'GabanEternal',
      email: 'dogooder@kittenmail.com',
      about:
        'I am a keen RPGer and love crafting suits of armour and weapons in my home forge. Have been interested in learning to grow mushrooms, and other plants. My Papillon - Pappy always steals my Lasercap, desperately need someone to teach me how to groom Pappy!.',
      rating: 5,
      region: 'Canterbury',
      picture: '/_terrance.jpg',
    },
    {
      id: 6,
      auth0_id: 'auth0|62734d140b600f00693e3f54',
      first_name: 'King',
      last_name: 'Korg',
      username: 'ladiesman217',
      email: 'korgbat79@hottiemail.com',
      about:
        'Would like to connect with any other Mandalorian refugees. Will teach Mandolore culinary arts in exchange for armor and weapons maintenance skills. I am also an experienced Blurrg racer. This is the way.',
      rating: 4,
      region: 'Waikato',
      picture: '/_king.jpeg',
    },
    {
      id: 7,
      auth0_id: 'auth0|62734d140b600f00693e3f55',
      first_name: 'Reginald',
      last_name: 'Voncraft Beer',
      username: 'Reggy',
      email: 'smidgearmy@gomail.xyz',
      about:
        'My interests are drinking, making and then drinking more beer. I am a competitive Salsa dancer and I also make my own shoes and toe socks.',
      rating: 5,
      region: 'Auckland',
      picture: '/_reginald.jpeg',
    },
    {
      id: 8,
      auth0_id: 'auth0|62734d140b600f00693e3f56',
      first_name: 'Karen',
      last_name: 'Cumberbatch',
      username: 'AuntKaren',
      email: 'dontcallmeabatch@batchery.com',
      about:
        'My passions are fine dining and high end handbags. I am an expert crypto-trader and can teach you how to sell NFTs back to yourself for tax minimisation strats. I do not provide any financial advice. Looking for a tennis partner/teacher and to improve my Spanish skills.',
      rating: 2,
      region: 'Auckland',
      picture: '/_karen.jpeg',
    },
    {
      id: 9,
      auth0_id: 'auth0|62734d140b600f00693e3f57',
      first_name: 'Brent',
      last_name: 'Office',
      username: 'NotOnlyfan',
      email: 'calmlaker444@retter.com',
      about:
        'Hi my name is Brent. I am new to this site and happy to meet you all. I am a keen fisherman and tinker around a lot with engines and motorbikes in my spare time. I would like to learn more about philosopy and meditation. Need to find a Yoga teacher.',
      rating: 1,
      region: 'Nelson Marlborough',
      picture: '/_brent.jpeg',
    },
    {
      id: 10,
      auth0_id: 'auth0|62734d140b600f00693e3f22',
      first_name: 'Cynthia',
      last_name: 'Pratt',
      username: 'bravenewdaydream',
      email: '12thCat@mail.com',
      about:
        'I am passionate about lockpicking, bass guitar and mid-16th century French antiques. I would interested in learning about post-modernism, and axe-throwing.',
      rating: 1,
      region: 'Nelson Marlborough',
      picture: '/_lisbeth.jpeg',
    },
  ])
}
